import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#0d1c2e",
        "inverse-primary": "#bec6e0",
        "error-container": "#ffdad6",
        "surface-tint": "#565e74",
        "surface-container-high": "#e2e7ff",
        "surface": "#faf8ff",
        "surface-bright": "#faf8ff",
        "tertiary-fixed-dim": "#b9c7df",
        "surface-container-low": "#f2f3ff",
        "on-surface": "#131b2e",
        "surface-container-highest": "#dae2fd",
        "surface-container": "#eaedff",
        "primary-fixed-dim": "#bec6e0",
        "secondary-fixed-dim": "#ffb77d",
        "on-secondary": "#ffffff",
        "secondary": "#904d00",
        "primary-container": "#131b2e",
        "outline-variant": "#c6c6cd",
        "on-secondary-container": "#663500",
        "background": "#faf8ff",
        "on-primary-container": "#7c839b",
        "primary-fixed": "#dae2fd",
        "secondary-fixed": "#ffdcc3",
        "primary": "#000000",
        "inverse-on-surface": "#eef0ff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fe932c",
        "on-primary-fixed": "#131b2e",
        "surface-variant": "#dae2fd",
        "on-tertiary-fixed": "#0d1c2e",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#77859a",
        "on-tertiary-fixed-variant": "#3a485b",
        "on-secondary-fixed": "#2f1500",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#6e3900",
        "outline": "#76777d",
        "surface-dim": "#d2d9f4",
        "tertiary": "#000000",
        "on-primary-fixed-variant": "#3f465c",
        "on-surface-variant": "#45464d",
        "inverse-surface": "#283044",
        "on-primary": "#ffffff",
        "on-background": "#131b2e",
        "error": "#ba1a1a",
        "tertiary-fixed": "#d5e3fc"
      },
      fontFamily: {
        "headline": ["var(--font-merriweather)"],
        "body": ["var(--font-inter)"],
        "label": ["var(--font-inter)"],
        sans: ['var(--font-inter)'],
        serif: ['var(--font-merriweather)'],
      },
    },
  },
  plugins: [],
}

export default config
